"""
Content Reviewer Agent - Reviews generated content objectively
"""
from utils.gemini_client import GeminiClient
from models.data_models import StyleGuide, ContentPiece, ReviewResult, FeedbackEntry
from typing import List
import json
import re


class ContentReviewer:
    """
    Objectively reviews content generated by ContentWriter.
    Checks alignment with style guide and feedback logs.
    Provides scores and actionable feedback.
    """

    def __init__(self, gemini_client: GeminiClient, pass_threshold: int = 80):
        """
        Initialize Content Reviewer

        Args:
            gemini_client: Gemini API client
            pass_threshold: Minimum score to pass review (0-100)
        """
        self.client = gemini_client
        self.pass_threshold = pass_threshold

    def review_content(self, content: ContentPiece,
                      style_guide: StyleGuide,
                      feedback_logs: List[FeedbackEntry]) -> ReviewResult:
        """
        Review a content piece against style guide and feedback history

        Args:
            content: Content to review
            style_guide: User's style guide
            feedback_logs: Historical feedback entries

        Returns:
            Review result with score and feedback
        """
        prompt = self._create_review_prompt(content, style_guide, feedback_logs)
        response = self.client.generate(prompt, temperature=0.3)

        # Parse review response
        review_result = self._parse_review_response(response)

        return review_result

    def _create_review_prompt(self, content: ContentPiece,
                             style_guide: StyleGuide,
                             feedback_logs: List[FeedbackEntry]) -> str:
        """Create prompt for reviewing content"""
        # Format style guide
        style_text = self._format_style_guide(style_guide)

        # Format recent feedback
        feedback_text = self._format_feedback_logs(feedback_logs)

        prompt = f"""You are a Content Reviewer. Your job is to objectively review LinkedIn posts for style alignment and quality.

CONTENT TO REVIEW:
Topic: {content.topic}
Post:
{content.content}

STYLE GUIDE (must align with this):
{style_text}

HISTORICAL FEEDBACK (issues to avoid):
{feedback_text if feedback_text else "No historical feedback yet."}

REVIEW CRITERIA:
1. Tone Alignment (25 points): Does it match the tone patterns in the style guide?
2. Structure Alignment (25 points): Does it follow the structure patterns?
3. Expression Usage (20 points): Uses common expressions naturally? Avoids avoided expressions?
4. Writing Quality (15 points): Clear, engaging, error-free?
5. LinkedIn Appropriateness (15 points): Suitable for LinkedIn audience?

Provide your review in the following JSON format:
{{
    "score": 85,
    "passed": true,
    "strengths": ["strength 1", "strength 2", ...],
    "issues": ["issue 1", "issue 2", ...],
    "suggestions": ["suggestion 1", "suggestion 2", ...],
    "detailed_feedback": "A paragraph explaining the score and key points"
}}

The score should be 0-100. Set "passed" to true if score >= {self.pass_threshold}, false otherwise.

Be objective and specific. If the content deviates from the style guide, clearly identify how.

Provide ONLY the JSON output, no additional text."""

        return prompt

    def _format_style_guide(self, style_guide: StyleGuide) -> str:
        """Format style guide for review prompt"""
        sections = []

        if style_guide.tone_patterns:
            sections.append("Tone Patterns:")
            for pattern in style_guide.tone_patterns:
                sections.append(f"  • {pattern.pattern}")

        if style_guide.structure_patterns:
            sections.append("Structure Patterns:")
            for pattern in style_guide.structure_patterns:
                sections.append(f"  • {pattern.pattern}")

        if style_guide.common_expressions:
            sections.append(f"Common Expressions: {', '.join(style_guide.common_expressions[:5])}")

        if style_guide.avoided_expressions:
            sections.append(f"Avoided Expressions: {', '.join(style_guide.avoided_expressions)}")

        return "\n".join(sections)

    def _format_feedback_logs(self, feedback_logs: List[FeedbackEntry],
                             limit: int = 5) -> str:
        """Format recent feedback for context"""
        if not feedback_logs:
            return ""

        recent = feedback_logs[-limit:]
        sections = []

        for fb in recent:
            if fb.specific_issues:
                sections.append(f"• Previous issues: {', '.join(fb.specific_issues)}")

        return "\n".join(sections) if sections else ""

    def _parse_review_response(self, response: str) -> ReviewResult:
        """
        Parse LLM review response into ReviewResult object

        Args:
            response: JSON response from LLM

        Returns:
            ReviewResult object
        """
        try:
            # Extract JSON from response
            start = response.find('{')
            end = response.rfind('}') + 1
            json_str = response[start:end]

            data = json.loads(json_str)

            return ReviewResult(
                score=float(data.get('score', 0)),
                passed=bool(data.get('passed', False)),
                strengths=data.get('strengths', []),
                issues=data.get('issues', []),
                suggestions=data.get('suggestions', []),
                detailed_feedback=data.get('detailed_feedback', '')
            )
        except Exception as e:
            print(f"Error parsing review response: {e}")
            print(f"Response: {response}")
            # Return a default failing review
            return ReviewResult(
                score=0,
                passed=False,
                issues=["Failed to parse review response"],
                detailed_feedback="Error in review process"
            )

    def format_review_for_display(self, review: ReviewResult) -> str:
        """
        Format review result for human-readable display

        Args:
            review: ReviewResult to format

        Returns:
            Formatted string
        """
        status = "✓ PASSED" if review.passed else "✗ FAILED"
        output = f"\n{'='*60}\n"
        output += f"REVIEW RESULT: {status} (Score: {review.score}/100)\n"
        output += f"{'='*60}\n\n"

        if review.strengths:
            output += "STRENGTHS:\n"
            for strength in review.strengths:
                output += f"  ✓ {strength}\n"
            output += "\n"

        if review.issues:
            output += "ISSUES:\n"
            for issue in review.issues:
                output += f"  ✗ {issue}\n"
            output += "\n"

        if review.suggestions:
            output += "SUGGESTIONS:\n"
            for suggestion in review.suggestions:
                output += f"  → {suggestion}\n"
            output += "\n"

        output += f"DETAILED FEEDBACK:\n{review.detailed_feedback}\n"
        output += f"{'='*60}\n"

        return output
